module.exports = new Map([
    ['INPUT_NAME',  'input name> '],
    ['INPUT_EMAIL',    'input email> '],
    ['INPUT_BUDGET', 'input budget> '],
    ['USER_ID', 'You id: '],
    ['USER_EMAIL', 'You email: '],
    ['USER_NAME', 'You name: '],
    ['USER_BUDGET', 'You budget: '],
    ['PRODUCT_TABLE_HEADER', 'id\tname\tprice'],
    ['PRODUCT_TABLE', 'Available products: '],
    ['INPUT_PRODUCT_ID', 'input product id> '],
    ['ERROR_INVALID_PRODUCT_ID', 'ERROR: invalid product id, try again\ninput product id> '],
    ['ERROR_NOT_ENOUGH_MONEY', 'ERROR: not enough money for order, try again'],
    ['SUCCESS', 'Order was successfully created'],
    ['ERROR_FILE', 'ERROR: reading file failed'],
    ['ERROR_DIRECTORY', 'ERROR: error with file directory!'],
    ['ORDERS_LIST', 'Orders:\n'],
]);
