DROP DATABASE IF EXISTS ttschool;
CREATE DATABASE ttschool;
USE ttschool;


CREATE TABLE school (
id INT(11) NOT NULL AUTO_INCREMENT,
school_name VARCHAR(50) NOT NULL,
y INT(11) NOT NULL ,
UNIQUE(school_name, y),
PRIMARY KEY(id)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `group`(
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
room VARCHAR(50) NOT NULL,
school_id INT(11) NOT NULL,
FOREIGN KEY (school_id) REFERENCES school (id) ON DELETE CASCADE,
PRIMARY KEY(id)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE trainee(
id INT(11) NOT NULL AUTO_INCREMENT,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
rating INT(11) NOT NULL,
group_id INT(11) DEFAULT NULL,
FOREIGN KEY (group_id) REFERENCES `group` (id) ON DELETE SET NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE subject (
id INT(11) NOT NULL AUTO_INCREMENT,
subject_name VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE subject_group(
id INT(11) NOT NULL AUTO_INCREMENT,
PRIMARY KEY(id),
subject_id INT(11) NOT NULL,
group_id INT(11) DEFAULT NULL,
FOREIGN KEY (group_id) REFERENCES `group` (id) ON DELETE SET NULL,
FOREIGN KEY (subject_id) REFERENCES subject(id) ON DELETE CASCADE,
UNIQUE KEY subject_group (subject_id, group_id)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

SELECT * from school;